In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv(f"M87_MWL2017_Rittick.txt", delimiter="\t", names=[
    "Instrument", "Band", "Frequency_Hz", "nu_Jy", "sigma_Fnu_Jy", "nuFnu_ergscm2", 
    "sigma_nuFnu_ergscm2", "Angular_Scale_arcsec", "date", "date_mjd"
])
df

,Instrument,Band,Frequency_Hz,nu_Jy,sigma_Fnu_Jy,nuFnu_ergscm2,sigma_nuFnu_ergscm2,Angular_Scale_arcsec,date,date_mjd
0,EVN,1.7GHZ,1.700000e+09,0.75,8.000000e-02,1.280000e-14,1.400000e-15,0.0050,2017-05-09,57882
1,HSA,8.4GHZ,8.400000e+09,1.30,1.300000e-01,1.090000e-13,1.100000e-14,0.0015,2017-05-15,57888
2,HSA,15GHZ,1.500000e+10,1.13,1.100000e-01,1.700000e-13,1.700000e-14,0.0010,2017-06-16,57889
3,HSA,24GHZ,2.400000e+10,1.22,1.200000e-01,2.930000e-13,2.900000e-14,0.0010,2017-05-20,57893
4,VERA,22GHZ,2.200000e+10,1.32,1.300000e-01,2.900000e-13,2.900000e-14,0.0010,2017-04-02,57845
...,...,...,...,...,...,...,...,...,...,...
62,VERITAS,281-397GEV,8.100000e+25,2.10-15,0.000000e+00,1.700000e-12,0.000000e+00,360.0000,2017-03-22,57834
63,VERITAS,398-562GEV,1.140000e+26,6.42E-16,3.420000e-16,7.320000e-13,3.900000e-14,360.0000,2017-03-22,57834
64,VERITAS,562-793GEV,1.610000e+26,4.02E-16,2.300000e-16,6.470000e-13,3.700000e-13,360.0000,2017-03-22,57834
65,VERITAS,793-1120GEV,2.280000e+26,4.22E-16,0.000000e+00,9.620000e-13,0.000000e+00,360.0000,2017-03-22,57834
66,VERITAS,120-1583GEV,3.220000e+26,4.51E-16,0.000000e+00,1.130000e-12,0.000000e+00,360.0000,2017-03-22,57834

In [3]:
df["nuFnu_1e-12ergscm2"] = df["nuFnu_ergscm2"] * 1e12
df["sigma_nuFnu_1e-12ergscm2"] = df["sigma_nuFnu_ergscm2"] * 1e12

df_new = df[["Instrument", "Frequency_Hz", "Angular_Scale_arcsec", "nuFnu_1e-12ergscm2", "sigma_nuFnu_1e-12ergscm2"]]
df_new

,Instrument,Frequency_Hz,Angular_Scale_arcsec,nuFnu_1e-12ergscm2,sigma_nuFnu_1e-12ergscm2
0,EVN,1.700000e+09,0.0050,0.0128,0.0014
1,HSA,8.400000e+09,0.0015,0.1090,0.0110
2,HSA,1.500000e+10,0.0010,0.1700,0.0170
3,HSA,2.400000e+10,0.0010,0.2930,0.0290
4,VERA,2.200000e+10,0.0010,0.2900,0.0290
...,...,...,...,...,...
62,VERITAS,8.100000e+25,360.0000,1.7000,0.0000
63,VERITAS,1.140000e+26,360.0000,0.7320,0.0390
64,VERITAS,1.610000e+26,360.0000,0.6470,0.3700
65,VERITAS,2.280000e+26,360.0000,0.9620,0.0000
66,VERITAS,3.220000e+26,360.0000,1.1300,0.0000

In [4]:
df_new.to_csv("../../M87data/data/SED/M87SED_EHTMWL2017.csv", index=False)